[package]
name = "trie-db"
version = "0.31.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
repository = "https://github.com/paritytech/trie"
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = { version = "0.4.22" }
smallvec = { version = "1.11.0", features = ["union", "const_new"] }
hash-db = { version = "0.16.0", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false, optional = true }

[features]
default = ["std"]
std = [
  "hash-db/std",
  "rustc-hex",
]
