[package]
name = "trie-db"
version = "0.30.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Merkle-Patricia Trie generic over key hasher and node encoding"
repository = "https://github.com/paritytech/trie"
license = "Apache-2.0"
edition = "2018"

[dependencies]
# REVERT: log = "0.4"
log = { version = "0.4.22" }
# REVERT: smallvec = { version = "1.0.0", features = ["union", "const_new"] }
smallvec = { version = "1.11.0", features = ["union", "const_new"] }
# REVERT: hash-db = { path = "../hash-db", default-features = false, version = "0.16.0"}
hash-db = { version = "0.16.0", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false, optional = true }

[features]
default = ["std"]
std = [
  "hash-db/std",
  "rustc-hex",
]
